// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnc9x7z8uq03c3KuLiwdZ-sPpFqIK5qlo',
    appId: '1:639971208772:web:acb2568a056b7225af1611',
    messagingSenderId: '639971208772',
    projectId: 'xmf01-22b85',
    authDomain: 'xmf01-22b85.firebaseapp.com',
    storageBucket: 'xmf01-22b85.firebasestorage.app',
    measurementId: 'G-D2X1B1TQMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQG-tMo7HJIt6kg4P4-eOdSexqklebeRY',
    appId: '1:639971208772:android:acff96a3ce5db040af1611',
    messagingSenderId: '639971208772',
    projectId: 'xmf01-22b85',
    storageBucket: 'xmf01-22b85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADchVf7mes_2y4IkFeVhDjiIVE6V2_APM',
    appId: '1:639971208772:ios:8fba9af9579ad721af1611',
    messagingSenderId: '639971208772',
    projectId: 'xmf01-22b85',
    storageBucket: 'xmf01-22b85.firebasestorage.app',
    iosBundleId: 'com.example.smartCalorieFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADchVf7mes_2y4IkFeVhDjiIVE6V2_APM',
    appId: '1:639971208772:ios:8fba9af9579ad721af1611',
    messagingSenderId: '639971208772',
    projectId: 'xmf01-22b85',
    storageBucket: 'xmf01-22b85.firebasestorage.app',
    iosBundleId: 'com.example.smartCalorieFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnc9x7z8uq03c3KuLiwdZ-sPpFqIK5qlo',
    appId: '1:639971208772:web:93c24f49762d59b3af1611',
    messagingSenderId: '639971208772',
    projectId: 'xmf01-22b85',
    authDomain: 'xmf01-22b85.firebaseapp.com',
    storageBucket: 'xmf01-22b85.firebasestorage.app',
    measurementId: 'G-38RT44GD04',
  );
}
